openapi: 3.1.0
info:
  title: Transaction webhooks
  description: 'After a transfer is booked in a balance account, Adyen sends webhooks
    with information about the transaction.


    You can use the data from these webhooks to, for example:

    - Update balances in your dashboards.

    - Keep track of incoming and outgoing funds.'
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
  version: '4'
  x-publicVersion: true
tags:
- name: General
components:
  schemas:
    Amount:
      type: object
      additionalProperties: false
      properties:
        currency:
          type: string
          description: The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes)
            of the amount.
          maxLength: 3
          minLength: 3
        value:
          type: integer
          format: int64
          description: The numeric value of the amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
      required:
      - currency
      - value
    BalancePlatformNotificationResponse:
      type: object
      additionalProperties: false
      properties:
        notificationResponse:
          type: string
          description: Respond with any **2xx** HTTP status code to [accept the webhook](https://docs.adyen.com/development-resources/webhooks/#accept-webhooks).
    BankCategoryData:
      type: object
      additionalProperties: false
      properties:
        priority:
          type: string
          description: 'The priority for the bank transfer. This sets the speed at
            which the transfer is sent and the fees that you have to pay. Required
            for transfers with `category` **bank**.


            Possible values:


            * **regular**: For normal, low-value transactions.


            * **fast**: A faster way to transfer funds, but the fees are higher. Recommended
            for high-priority, low-value transactions.


            * **wire**: The fastest way to transfer funds, but this has the highest
            fees. Recommended for high-priority, high-value transactions.


            * **instant**: For instant funds transfers within the United States and
            in [SEPA locations](https://www.ecb.europa.eu/paym/integration/retail/sepa/html/index.en.html).


            * **crossBorder**: For high-value transfers to a recipient in a different
            country.


            * **internal**: For transfers to an Adyen-issued business bank account
            (by bank account number/IBAN).'
          enum:
          - crossBorder
          - fast
          - instant
          - internal
          - regular
          - wire
          x-addedInVersion: '4'
        type:
          type: string
          default: bank
          description: '**bank**'
          enum:
          - bank
    InternalCategoryData:
      type: object
      additionalProperties: false
      properties:
        modificationMerchantReference:
          type: string
          description: The capture's merchant reference included in the transfer.
          x-addedInVersion: '4'
        modificationPspReference:
          type: string
          description: The capture reference included in the transfer.
          x-addedInVersion: '4'
        type:
          type: string
          default: internal
          description: '**internal**'
          enum:
          - internal
    IssuedCard:
      type: object
      additionalProperties: false
      properties:
        authorisationType:
          type: string
          description: The authorisation type. For example, **defaultAuthorisation**,
            **preAuthorisation**, **finalAuthorisation**
          x-addedInVersion: '4'
        networkVariant:
          type: string
          description: The card variant associated with the payment network used to
            route or process the transaction. For single-network cards, this matches
            the `brandVariant`. For US dual-network cards routed over an alternate
            network, this value reflects the specific tier or sub-type under that
            processing network.
          enum:
          - maestro_us
          - mastercard
          - visa
          x-addedInVersion: '4'
        panEntryMode:
          type: string
          description: 'Indicates the method used for entering the PAN to initiate
            a transaction.


            Possible values: **manual**, **chip**, **magstripe**, **contactless**,
            **cof**, **ecommerce**, **token**.'
          enum:
          - chip
          - cof
          - contactless
          - ecommerce
          - magstripe
          - manual
          - token
          x-addedInVersion: '4'
        processingType:
          type: string
          description: 'Contains information about how the payment was processed.


            Possible values: **atmWithdraw**, **balanceInquiry**, **ecommerce**, **moto**,
            **pos**, **purchaseWithCashback**, **recurring**, **token**.'
          enum:
          - atmWithdraw
          - balanceInquiry
          - ecommerce
          - moto
          - pos
          - purchaseWithCashback
          - recurring
          - token
          x-addedInVersion: '4'
        relayedAuthorisationData:
          $ref: '#/components/schemas/RelayedAuthorisationData'
          description: If you are using relayed authorisation, this object contains
            information from the relayed authorisation response from your server.
          x-addedInVersion: '4'
        schemeTraceId:
          type: string
          description: The identifier of the original payment. This ID is provided
            by the scheme and can be alphanumeric or numeric, depending on the scheme.
            The `schemeTraceID` should refer to an original `schemeUniqueTransactionID`
            provided in an earlier payment (not necessarily processed by Adyen). A
            `schemeTraceId` is typically available for authorization adjustments or
            recurring payments.
          x-addedInVersion: '4'
        schemeUniqueTransactionId:
          type: string
          description: The unique identifier created by the scheme. This ID can be
            alphanumeric or numeric depending on the scheme.
          x-addedInVersion: '4'
        threeDSecure:
          $ref: '#/components/schemas/ThreeDSecure'
          description: The data of the result from the 3DS authentication.
          x-addedInVersion: '4'
        type:
          type: string
          default: issuedCard
          description: '**issuedCard**'
          enum:
          - issuedCard
        validationFacts:
          type: array
          description: The evaluation of the validation facts. See [validation checks](https://docs.adyen.com/issuing/validation-checks)
            for more information.
          items:
            $ref: '#/components/schemas/TransferNotificationValidationFact'
          x-addedInVersion: '4'
    PaymentInstrument:
      type: object
      additionalProperties: false
      properties:
        description:
          type: string
          description: The description of the resource.
        id:
          type: string
          description: The unique identifier of the resource.
        reference:
          type: string
          description: The reference for the resource.
        tokenType:
          type: string
          description: The type of wallet that the network token is associated with.
          x-addedInVersion: '3'
    PlatformPayment:
      type: object
      additionalProperties: false
      properties:
        modificationMerchantReference:
          type: string
          description: The capture's merchant reference included in the transfer.
          x-addedInVersion: '4'
        modificationPspReference:
          type: string
          description: The capture reference included in the transfer.
          x-addedInVersion: '4'
        paymentMerchantReference:
          type: string
          description: The payment's merchant reference included in the transfer.
          x-addedInVersion: '4'
        platformPaymentType:
          type: string
          description: 'Specifies the nature of the transfer. This parameter helps
            categorize transfers so you can reconcile transactions at a later time,
            using the Balance Platform Accounting Report for [marketplaces](https://docs.adyen.com/marketplaces/reports-and-fees/balance-platform-accounting-report/)
            or [platforms](https://docs.adyen.com/platforms/reports-and-fees/balance-platform-accounting-report/).


            Possible values:


            * **AcquiringFees**: The acquiring fee (the aggregated amount of interchange
            and scheme fee) incurred on a transaction.


            * **AdyenCommission**: The transaction fee due to Adyen under [blended
            rates](https://www.adyen.com/knowledge-hub/guides/payments-training-guide/get-the-best-from-your-card-processing).


            * **AdyenFees**: All transaction fees due to Adyen. This is the aggregated
            amount of Adyen''s commission and markup.


            * **AdyenMarkup**: The transaction fee due to Adyen under [Interchange++
            pricing](https://www.adyen.com/pricing).


            * **BalanceAccount**: The amount booked to your user after the deduction
            of the relevant fees.


            * **Commission**: Your platform''s or marketplace''s commission on a transaction.


            * **DCCPlatformCommission**: **deprecated** The Dynamic Currency Conversion
            (DCC) fee on a transaction.


            * **DCCMarkup**: The Dynamic Currency Conversion (DCC) fee on a transaction.


            * **Interchange**: The interchange fee (fee paid to the issuer) incurred
            on a transaction.


            * **PaymentFee**: The aggregated amount of all transaction fees.


            * **Remainder**: The leftover amount after currency conversion.


            * **SchemeFee**: The scheme fee incurred on a transaction.


            * **Surcharge**: The surcharge paid by the customer on a transaction.


            * **Tip**: The tip paid by the customer.


            * **TopUp**: An incoming transfer to top up your user''s balance account.


            * **VAT**: The value-added tax charged on the payment.'
          enum:
          - AcquiringFees
          - AdyenCommission
          - AdyenFees
          - AdyenMarkup
          - BalanceAccount
          - ChargebackRemainder
          - Commission
          - DCCMarkup
          - DCCPlatformCommission
          - Default
          - Interchange
          - PaymentFee
          - Remainder
          - SchemeFee
          - Surcharge
          - Tip
          - TopUp
          - VAT
          x-addedInVersion: '4'
        pspPaymentReference:
          type: string
          description: The payment reference included in the transfer.
          x-addedInVersion: '4'
        type:
          type: string
          default: platformPayment
          description: '**platformPayment**'
          enum:
          - platformPayment
    RelayedAuthorisationData:
      type: object
      additionalProperties: false
      properties:
        metadata:
          type: object
          additionalProperties:
            type: string
          description: Contains key-value pairs of your references and descriptions,
            for example, `customId`:`your-own-custom-field-12345`.
          x-addedInVersion: '3'
        reference:
          type: string
          description: Your reference for the relayed authorisation data.
          x-addedInVersion: '3'
    Resource:
      type: object
      additionalProperties: false
      properties:
        balancePlatform:
          type: string
          description: The unique identifier of the balance platform.
        creationDate:
          type: string
          format: date-time
          description: The date and time when the event was triggered, in ISO 8601
            extended format. For example, **2025-03-19T10:15:30+01:00**.
        id:
          type: string
          description: The ID of the resource.
    ResourceReference:
      type: object
      additionalProperties: false
      properties:
        description:
          type: string
          description: The description of the resource.
        id:
          type: string
          description: The unique identifier of the resource.
        reference:
          type: string
          description: The reference for the resource.
    ThreeDSecure:
      type: object
      additionalProperties: false
      properties:
        acsTransactionId:
          type: string
          description: The transaction identifier for the Access Control Server
          x-addedInVersion: '4'
    Transaction:
      type: object
      additionalProperties: false
      properties:
        accountHolder:
          $ref: '#/components/schemas/ResourceReference'
          description: Contains information about the account holder associated with
            the `balanceAccount`.
          x-addedInVersion: '4'
        amount:
          $ref: '#/components/schemas/Amount'
          description: Contains information about the amount of the transaction.
          x-addedInVersion: '1'
        balanceAccount:
          $ref: '#/components/schemas/ResourceReference'
          description: Contains information about the balance account involved in
            the transaction.
          x-addedInVersion: '4'
        balancePlatform:
          type: string
          description: The unique identifier of the balance platform.
          x-addedInVersion: '1'
        bookingDate:
          type: string
          format: date-time
          description: The date the transaction was booked into the balance account.
          x-addedInVersion: '1'
        creationDate:
          type: string
          format: date-time
          description: The date and time when the event was triggered, in ISO 8601
            extended format. For example, **2025-03-19T10:15:30+01:00**.
        description:
          type: string
          description: The `description` from the `/transfers` request.
          x-addedInVersion: '1'
        id:
          type: string
          description: The unique identifier of the transaction.
          x-addedInVersion: '1'
        paymentInstrument:
          $ref: '#/components/schemas/PaymentInstrument'
          description: Contains information about the payment instrument that was
            used for the transaction.
          x-addedInVersion: '4'
        referenceForBeneficiary:
          type: string
          description: "The reference sent to or received from the counterparty.\n\
            \n* For outgoing funds, this is the [`referenceForBeneficiary`](https://docs.adyen.com/api-explorer/#/transfers/latest/post/transfers__resParam_referenceForBeneficiary)\
            \ from the  [`/transfers`](https://docs.adyen.com/api-explorer/#/transfers/latest/post/transfers__reqParam_referenceForBeneficiary)\
            \ request.\n\n * For incoming funds, this is the reference from the sender."
          x-addedInVersion: '1'
        status:
          type: string
          description: "The status of the transaction.\n\n Possible values:\n\n* **pending**:\
            \ The transaction is still pending.\n\n* **booked**: The transaction has\
            \ been booked to the balance account.\n\n"
          enum:
          - booked
          - pending
          x-addedInVersion: '1'
        transfer:
          $ref: '#/components/schemas/TransferView'
          description: Contains information about the transfer related to the transaction.
          x-addedInVersion: '4'
        valueDate:
          type: string
          format: date-time
          description: The date the transfer amount becomes available in the balance
            account.
          x-addedInVersion: '1'
      required:
      - accountHolder
      - amount
      - balanceAccount
      - balancePlatform
      - bookingDate
      - id
      - status
      - valueDate
    TransactionNotificationRequestV4:
      type: object
      additionalProperties: false
      properties:
        data:
          $ref: '#/components/schemas/Transaction'
          description: Contains details about the event.
        environment:
          type: string
          description: 'The environment from which the webhook originated.


            Possible values: **test**, **live**.'
        timestamp:
          type: string
          format: date-time
          description: When the event was queued.
        type:
          type: string
          description: Type of the webhook.
          enum:
          - balancePlatform.transaction.created
      required:
      - data
      - environment
    TransferNotificationValidationFact:
      type: object
      additionalProperties: false
      properties:
        result:
          type: string
          description: The evaluation result of the validation fact.
        type:
          type: string
          description: The type of the validation fact.
    TransferView:
      type: object
      additionalProperties: false
      properties:
        categoryData:
          description: The relevant data according to the transfer category.
          discriminator:
            propertyName: type
            mapping:
              issuedCard: '#/components/schemas/IssuedCard'
              platformPayment: '#/components/schemas/PlatformPayment'
              bank: '#/components/schemas/BankCategoryData'
              internal: '#/components/schemas/InternalCategoryData'
          oneOf:
          - $ref: '#/components/schemas/BankCategoryData'
          - $ref: '#/components/schemas/InternalCategoryData'
          - $ref: '#/components/schemas/IssuedCard'
          - $ref: '#/components/schemas/PlatformPayment'
          x-addedInVersion: '4'
        id:
          type: string
          description: The ID of the resource.
        reference:
          type: string
          description: The [`reference`](https://docs.adyen.com/api-explorer/#/transfers/latest/post/transfers__reqParam_reference)
            from the `/transfers` request. If you haven't provided any, Adyen generates
            a unique reference.
          x-addedInVersion: '4'
      required:
      - reference
  examples:
    post-balancePlatform.transaction.created-01.balancePlatform-transaction-created-payout-ti:
      summary: Transaction related to a payout
      description: Example webhook for a transaction related to a payout to a transfer
        instrument
      value:
        data:
          id: EVJN00000000000000000000000003EUR
          amount:
            value: -10000
            currency: EUR
          status: booked
          transfer:
            categoryData:
              priority: regular
              type: bank
            id: 3JNC3O5ZVFLLGV4B
            reference: ' Your internal reference for the transfer'
          valueDate: '2023-08-11T16:19:35+02:00'
          bookingDate: '2023-08-11T16:31:02+02:00'
          creationDate: '2023-08-11T16:19:35+02:00'
          description: Your description of the transfer
          referenceForBeneficiary: Your reference sent to the beneficiary of the transfer
          accountHolder:
            id: AH00000000000000000000001
            reference: Your reference for the account holder
            description: Your description of the account holder
          balanceAccount:
            id: BA00000000000000000000001
            description: Your description of the balance account from where the amount
              is debited.
          balancePlatform: YOUR_BALANCE_PLATFORM
        environment: test
        timestamp: '2023-08-11T16:16:35+02:00'
        type: balancePlatform.transaction.created
    post-balancePlatform.transaction.created-02.balancePlatform-transaction-created-internal-incoming:
      summary: Transaction related to an incoming internal transfer
      description: Example webhook for a transaction related to an incoming internal
        transfer
      value:
        data:
          id: EVJN00000000000000000000000003EUR
          amount:
            value: 10000
            currency: EUR
          status: booked
          transfer:
            categoryData:
              type: internal
            id: 48TYZO5ZVURJ2FCW
            reference: ' Your internal reference for the transfer'
          valueDate: '2023-08-11T16:19:35+02:00'
          bookingDate: '2023-08-11T16:31:02+02:00'
          creationDate: '2023-08-11T16:19:35+02:00'
          description: The sender's of the transfer
          referenceForBeneficiary: The sender's reference sent to the beneficiary
            of the transfer
          accountHolder:
            id: AH00000000000000000000001
            reference: Your reference for the account holder
            description: Your description of the account holder
          balanceAccount:
            id: BA00000000000000000000001
            description: Your description of the balance account from where the amount
              is debited.
          balancePlatform: YOUR_BALANCE_PLATFORM
        environment: test
        timestamp: '2023-08-11T16:16:35+02:00'
        type: balancePlatform.transaction.created
    post-balancePlatform.transaction.created-03.balancePlatform-transaction-created-outgoing-business-account:
      summary: Transaction related to an outgoing bank transfer
      description: Example webhook for a transaction related to an outgoing bank transfer
      value:
        data:
          id: EVJN00000000000000000000000003EUR
          amount:
            value: -10000
            currency: EUR
          status: booked
          transfer:
            categoryData:
              priority: regular
              type: bank
            id: 3JNC3O5ZVFLLGV4B
            reference: ' Your internal reference for the transfer'
          valueDate: '2023-08-11T16:19:35+02:00'
          bookingDate: '2023-08-11T16:31:02+02:00'
          creationDate: '2023-08-11T16:19:35+02:00'
          description: Your description of the transfer
          referenceForBeneficiary: Your reference sent to the beneficiary of the transfer
          accountHolder:
            id: AH00000000000000000000001
            reference: Your reference for the account holder
            description: Your description of the account holder
          balanceAccount:
            id: BA00000000000000000000001
            description: Your description of the balance account from where the amount
              is debited.
          paymentInstrument:
            id: PI00000000000000000000001
            description: Your description of the payment instrument
          balancePlatform: YOUR_BALANCE_PLATFORM
        environment: test
        timestamp: '2023-08-11T16:16:35+02:00'
        type: balancePlatform.transaction.created
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
webhooks:
  balancePlatform.transaction.created:
    post:
      tags:
      - General
      summary: Transaction created
      description: 'After a transfer is booked in a balance account, Adyen sends this
        webhook with information about the transaction.


        '
      operationId: post-balancePlatform.transaction.created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionNotificationRequestV4'
            examples:
              01.balancePlatform-transaction-created-payout-ti:
                $ref: '#/components/examples/post-balancePlatform.transaction.created-01.balancePlatform-transaction-created-payout-ti'
              02.balancePlatform-transaction-created-internal-incoming:
                $ref: '#/components/examples/post-balancePlatform.transaction.created-02.balancePlatform-transaction-created-internal-incoming'
              03.balancePlatform-transaction-created-outgoing-business-account:
                $ref: '#/components/examples/post-balancePlatform.transaction.created-03.balancePlatform-transaction-created-outgoing-business-account'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalancePlatformNotificationResponse'
      security:
      - BasicAuth: []
      x-addedInVersion: '1'
      x-sortIndex: 0
      x-methodName: transactionCreated
