openapi: 3.1.0
servers:
- url: https://obgateway-test.adyen.com/obgateway/v1
  description: Test Environment
- url: https://obgateway-live.adyen.com/obgateway/v1
  description: Live Environment
info:
  title: Open Banking API
  description: "The Open Banking API provides secure endpoints to share financial\
    \ data and services with third parties. This API offers quick and reliable user\
    \ verification.\n\nWith these endpoints, you can:\n\n- **Create a list of available\
    \ account verification routes**: Create a list of Account Information Service\
    \ Providers (AISPs) for third-party individual account verification. Successful\
    \ connections generate a unique code used for requesting bank reports and verifying\
    \ identity.\n- **Verify bank account ownership**: Get the account verification\
    \ report using the unique code from a successful open banking connection. This\
    \ report provides identity verification and bank account details.\n## Authentication\n\
    Each request made to the Open Banking API must be signed with an API key. Generate\
    \ an API key in your Customer Area.\n\nTo connect to the API, add an X-API-Keyheader\
    \ with the API key as the value, for example:\n\n ```\ncurl\n-H \"Content-Type:\
    \ application/json\" \n-H \"X-API-Key: YOUR_API_KEY\" \n...\n```\n\n## Roles and\
    \ permissions\nTo use the Open Banking API, your API credential must have the\
    \ following roles:\n- **Role for OpenBanking account verification use case: EXTERNAL**\n\
    \nReach out to your Adyen contact to set up these roles.\n"
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
  version: '1'
  x-timestamp: '2025-09-16T12:06:38Z'
tags:
- name: Account Verification
  x-groupIndex: 1
paths:
  /accountVerification/routes:
    post:
      tags:
      - Account Verification
      summary: Create routes for account verification
      description: Create a list of routes for verifying bank accounts of third-party
        individuals. Successful connections generate a unique code used for requesting
        bank reports and verifying identity.
      operationId: post-accountVerification-routes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountVerificationRoutesRequest'
            examples:
              Account verification routes request:
                summary: List AISP Routes for account verification
                description: Specifies the country, locale, state, and redirect URL
                  to initiate the account verification process and receive available
                  bank routes.
                value:
                  country: NL
                  locale: en-US
                  state: 11a1e60a-18b0-4dda-9258-e0ae29e1e2a3
                  redirectUrl: https://merchanturl.example.org/redirect/url
        required: true
      responses:
        '200':
          description: OK - The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountVerificationRoutesResponse'
              examples:
                Account verification routes response:
                  summary: Response detailing available bank routes for account verification
                  description: Returns a list of bank providers available for account
                    verification in the specified country, along with their respective
                    redirection URLs to initiate the authentication flow.
                  value:
                    routes:
                    - provider:
                        name: Tink
                        logoURL: https://obgateway.adyen.com/obgateway/static/provider/images/tink-logo.svg
                      link: https://obgateway.adyen.com/obgateway/provider/outgoing/tink/redirect/13ec4802-c987-4f8c-8909-9a75ff567256
        '400':
          description: Bad Request - The request is malformed or is not in the expected
            format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '401':
          description: Unauthorized - The API credential used in the request is invalid
            or does not have the right permissions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '422':
          description: Unprocessable Entity - A request validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '429':
          description: Too Many Requests - Request rate limit exceeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '500':
          description: Internal Service Error - An unrecoverable error occurred while
            trying to perform the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
      x-methodName: createAccountVerificationRoutes
      x-sortIndex: 1
  /accountVerification/reports/{code}:
    get:
      tags:
      - Account Verification
      summary: Get account verification report
      description: Get the account verification report using a unique code from a
        successful open banking connection. This report provides identity verification
        and bank account details.
      operationId: get-accountVerification-reports-code
      parameters:
      - name: code
        in: path
        description: The unique code you receive after a successful open banking flow
          that is included as a query parameter in the `redirectUrl` callback.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK - The request has succeeded.
          headers:
            X-State:
              style: simple
              schema:
                description: The state provided in the routes generation request.
                example: 123A-456B-789C-10D
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountVerificationReportResponse'
              examples:
                Account verification report (IBAN):
                  summary: Account verification report for an IBAN account
                  description: Provides a detailed report of verified IBAN account.
                  value:
                    id: 69ee9452ef824fe092f1417f37535755
                    country: ES
                    accounts:
                    - accountId: ed5080e4f485430290475d246534c8fd
                      accountType: CURRENT
                      accountName: Checking Account 1
                      accountNumber: ES1376230223254275408743
                      currency: EUR
                      identifiers:
                        iban:
                          iban: ES1376230223254275408743
                          bban: '76230223254275408743'
                      parties:
                      - identity:
                          fullLegalName: Alberta Bobbeth Charleson
                          name: Alberta Bobbeth Charleson
                        role: HOLDER
                      bankName: Tink Demo Bank
                Account verification report (ACH):
                  summary: Account verification report for an ACH account
                  description: Provides a detailed report of verified ACH account.
                  value:
                    id: nJwJE68h6vlSEnk
                    country: US
                    accounts:
                    - accountId: XvNzLGMpl3fBevllWEwks3jvBvPy88sbkypkP
                      accountType: CURRENT
                      accountName: Plaid Gold Standard 0% Interest Checking
                      accountNumber: '1111222233330000'
                      currency: USD
                      identifiers:
                        ach:
                          accountNumber: '1111222233330000'
                          routingNumber: '011401533'
                      parties:
                      - identity:
                          fullLegalName: Jane Doe
                          name: Jane Doe
                        role: HOLDER
                      bankName: Wells Fargo
                    - accountId: XvNzLGMpl3fBevllWEwks3jvBvPy88sbkypkP
                      accountType: CURRENT
                      accountName: Plaid Gold Standard 0% Interest Checking
                      accountNumber: '3333222211110000'
                      currency: USD
                      identifiers:
                        ach:
                          accountNumber: '3333222211110000'
                          routingNumber: 033587521
                      parties:
                      - identity:
                          fullLegalName: Jane Doe
                          name: Jane Doe
                        role: HOLDER
                      bankName: Bank of America
                Account verification report (EFT):
                  summary: Account verification report for an EFT account
                  description: Provides a detailed report of verified EFT account.
                  value:
                    id: 69ee9452ef824fe092f1417f37535755
                    country: CA
                    accounts:
                    - accountId: th7681t6j876930300478t246534j8fi
                      accountType: CURRENT
                      accountName: Checking Account 1
                      accountNumber: '111122220000'
                      currency: CAD
                      identifiers:
                        eft:
                          accountNumber: '111122220000'
                          branch: '01533'
                          institution: '114'
                      parties:
                      - identity:
                          fullLegalName: Jessie Dean
                          name: Jessie Dean
                        role: HOLDER
                      bankName: Plaid Demo Bank
                Account verification report (BSB):
                  summary: Account verification report for a BSB account
                  description: Provides a detailed report of verified BSB account.
                  value:
                    id: lkumovjdFQFy6JhbSaWTa8sCH79fzJJnFMKpkSST09ism2lCMlsnSEsrjx6XNr4u_kxhSg==
                    country: AU
                    accounts:
                    - accountId: lkumovjdFQFy6JhbSaWTa8sCH79fzJJnFMKpkSST09ism2lCMlsnSEsrjx6XNr4u_kxhSg==
                      accountType: UNKNOWN
                      accountName: Savings Account
                      accountNumber: '37458052'
                      currency: AUD
                      identifiers:
                        bsb:
                          accountNumber: '37458052'
                          bsbCode: '413574'
                      parties:
                      - identity:
                          fullLegalName: Peter Sherman
                          name: Peter
                        role: HOLDER
                      bankName: Banking Sandbox Data Holder
        '400':
          description: Bad Request - The request is malformed or is not in the expected
            format.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '401':
          description: Unauthorized - The API credential used in the request is invalid
            or does not have the right permissions.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '404':
          description: Not Found - The entity was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '422':
          description: Unprocessable Entity - A request validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '429':
          description: Too Many Requests - Request rate limit exceeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
        '500':
          description: Internal Service Error - An unrecoverable error occurred while
            trying to perform the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponseEntity'
      x-methodName: getAccountVerificationReport
      x-sortIndex: 2
components:
  schemas:
    AccountVerificationCountry:
      type: string
      enum:
      - SE
      - FI
      - 'NO'
      - DK
      - NL
      - IT
      - DE
      - AT
      - ES
      - PT
      - FR
      - GB
      - BE
      - LV
      - LT
      - PL
      - EE
      - IE
      - US
      - CA
      - AU
    AccountVerificationRoutesRequest:
      required:
      - country
      - redirectUrl
      type: object
      properties:
        country:
          description: The location where the third-party individual's bank account
            is registered. Adyen uses this information to determine an available open
            banking provider, and to configure the open banking flow for that respective
            location.
          $ref: '#/components/schemas/AccountVerificationCountry'
        locale:
          type: string
          description: 'The language to use in the open banking flow UI, specified
            by a combination of a two-letter [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)
            language code and an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
            country code.


            This information is used to configure the open banking flow with the same
            language for a consistent user experience.


            Default value: **en-US**'
        redirectUrl:
          type: string
          description: The URL where Adyen redirects the third-party individual after
            they complete the open banking flow.
          format: url
        state:
          type: string
          description: A value that helps you identify the request in callback handling.
            You can generate this value on a per-session basis to protect the callback
            against Cross-Site Request Forgery (CSRF) attacks. This value  must be
            composed of characters that can be successfully URL-encoded.
    AccountVerificationRoutesResponse:
      required:
      - routes
      type: object
      properties:
        routes:
          type: array
          description: This array lists available open banking redirection links,
            each with its associated provider metadata.
          items:
            $ref: '#/components/schemas/Route'
    Provider:
      required:
      - logoURL
      - name
      type: object
      properties:
        logoURL:
          type: string
          description: The URL of the organization's or brand's logo. This URL typically
            points to an image file (e.g., .png, .jpg, .svg) that can be displayed
            to visually represent the entity.
        name:
          type: string
          description: The official or commonly used name of the organization, brand,
            or entity.
    Route:
      required:
      - link
      - provider
      type: object
      properties:
        link:
          type: string
          description: The redirection link. You can use this link to redirect the
            user to the open banking flow when the user selects it.
        provider:
          description: Metadata about the selected provider, including the name and
            company logo. You can use this information to inform the user about the
            provider they will be redirected to when they select the link.
          $ref: '#/components/schemas/Provider'
    DefaultErrorResponseEntity:
      type: object
      properties:
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of
            the problem.
        errorCode:
          type: string
          description: Unique business error code.
        instance:
          type: string
          description: A URI that identifies the specific occurrence of the problem
            if applicable.
        invalidFields:
          type: array
          description: Array of fields with validation errors when applicable.
          items:
            $ref: '#/components/schemas/InvalidField'
        requestId:
          type: string
          description: The unique reference for the request.
        status:
          type: integer
          description: The HTTP status code.
          format: int32
        title:
          type: string
          description: A short, human-readable summary of the problem type.
        type:
          type: string
          description: A URI that identifies the validation error type. It points
            to human-readable documentation for the problem type.
      description: Standardized error response following RFC-7807 format
      externalDocs:
        url: https://www.rfc-editor.org/rfc/rfc7807
    InvalidField:
      required:
      - message
      - name
      - value
      type: object
      properties:
        name:
          type: string
          description: The field that has an invalid value.
        value:
          type: string
          description: The invalid value.
        message:
          type: string
          description: Description of the validation error.
    ACHAccountIdentifier:
      required:
      - accountNumber
      - routingNumber
      type: object
      properties:
        accountLastDigits:
          type: string
          description: The last digits of the account number. If the accountNumber
            is tokenized, this field contains the last digits of the non-tokenized
            account number. This helps users verify the account without seeing the
            full number.
        accountNumber:
          type: string
          description: The account number of the bank account.
        isTokenized:
          type: boolean
          description: Indicates whether the account number is tokenized. A tokenized
            account number is a unique ID generated by a bank to protect the user's
            actual account number.
        routingNumber:
          type: string
          description: The [routing number](https://en.wikipedia.org/wiki/ABA_routing_transit_number),
            without separators or whitespace.
    AccountIdentifiers:
      type: object
      properties:
        ach:
          description: Identifiers relevant for Automated Clearing House (ACH) payments,
            primarily used in the United States.
          $ref: '#/components/schemas/ACHAccountIdentifier'
        bacs:
          description: Identifiers relevant for Bankers' Automated Clearing Services
            (BACS) payments, primarily used in the United Kingdom.
          $ref: '#/components/schemas/BACSAccountIdentifier'
        bsb:
          description: Identifiers relevant for Australian banking, specifically for
            BSB (Bank-State-Branch) numbers.
          $ref: '#/components/schemas/BSBAccountIdentifier'
        eft:
          description: Identifiers relevant for Electronic Funds Transfer (EFT) payments,
            commonly used in Canada.
          $ref: '#/components/schemas/EFTAccountIdentifier'
        iban:
          description: The international bank account number as defined in the ISO-13616
            standard.
          $ref: '#/components/schemas/IBANAccountIdentifier'
        rix:
          description: Identifiers relevant for the Rix (Russian Interbank eXchange)
            system, used for interbank payments within Russia.
          $ref: '#/components/schemas/RIXAccountIdentifier'
    AccountParty:
      required:
      - identity
      - role
      type: object
      properties:
        identity:
          description: Contains the identity details of the party.
          $ref: '#/components/schemas/Identity'
        role:
          description: Specifies a role or capacity of the party in relation to the
            bank account.
          $ref: '#/components/schemas/PartyRole'
    AccountType:
      type: string
      enum:
      - CURRENT
      - SAVINGS
      - BUSINESS
      - CREDIT_CARD
      - LOAN
      - UNKNOWN
    AccountVerificationReportResponse:
      required:
      - accounts
      - country
      - id
      type: object
      properties:
        accounts:
          type: array
          description: A list of bank accounts with their respective information.
          items:
            $ref: '#/components/schemas/VerifiedAccount'
        country:
          description: The location where the third-party individual's bank account
            is registered.
          $ref: '#/components/schemas/AccountVerificationCountry'
        id:
          type: string
          description: The unique identifier for the specific report.
    BACSAccountIdentifier:
      required:
      - accountNumber
      - sortCode
      type: object
      properties:
        accountNumber:
          type: string
          description: The account number of the bank account.
        sortCode:
          type: string
          description: A number that identifies the specific bank and branch where
            a UK bank account is held.
    BSBAccountIdentifier:
      required:
      - accountNumber
      - bsbCode
      type: object
      properties:
        accountNumber:
          type: string
          description: The account number of the bank account.
        bsbCode:
          type: string
          description: The BSB (Bank-State-Branch) code.
    EFTAccountIdentifier:
      required:
      - accountNumber
      - branch
      - institution
      type: object
      properties:
        accountNumber:
          type: string
          description: The account number of the bank account.
        branch:
          type: string
          description: Identifies the specific branch where the account is held within
            the Canadian banking system.
        institution:
          type: string
          description: The financial institution that identifies the bank in Canada.
    IBANAccountIdentifier:
      required:
      - bban
      - bic
      - iban
      type: object
      properties:
        bban:
          type: string
          description: The Basic Bank Account Number (BBAN) component of the IBAN.
        bic:
          type: string
          description: BIC of a bank account.
        iban:
          type: string
          description: The international bank account number as defined in the [ISO-13616](https://www.iso.org/standard/81090.html)
            standard. This is the national identifier for the bank account, following
            the country-specific format, and is part of the full IBAN.
    Identity:
      required:
      - fullLegalName
      - name
      type: object
      properties:
        fullLegalName:
          type: string
          description: The complete legal name of the individual or entity.
        name:
          type: string
          description: A commonly used or human-readable name for the individual or
            entity.
    PartyRole:
      type: string
      enum:
      - HOLDER
      - AUTHORIZED_USER
      - OTHER
      - UNKNOWN
    RIXAccountIdentifier:
      required:
      - accountNumber
      - clearingNumber
      type: object
      properties:
        accountNumber:
          type: string
          description: The account number of the bank account.
        clearingNumber:
          type: string
          description: The 4- to 5-digit clearing number, without separators or whitespace.
    VerifiedAccount:
      required:
      - accountId
      - accountName
      - accountNumber
      - accountType
      - currency
      - identifiers
      - parties
      type: object
      properties:
        accountId:
          type: string
          description: The unique identifier for the bank account.
        accountName:
          type: string
          description: The name of the bank account. This name is assigned by the
            banking institution, and it describes the type of bank account.
        accountNumber:
          type: string
          description: The account number of the bank account.
        accountType:
          description: The type of the bank account. Possible values are **CURRENT**,
            **SAVINGS**, **BUSINESS**, **CREDIT_CARD**, **LOAN**, **UNKNOWN**.
          $ref: '#/components/schemas/AccountType'
        bankName:
          type: string
          description: The name of the banking institution where the bank account
            is held.
        currency:
          type: string
          description: The currency of the funds in the bank account.
        identifiers:
          description: Contains various codes and details used to uniquely identify
            the bank account across different regions.
          $ref: '#/components/schemas/AccountIdentifiers'
        parties:
          type: array
          description: Contains details of all parties associated with the report.
          items:
            $ref: '#/components/schemas/AccountParty'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    BasicAuth:
      type: http
      scheme: basic
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
