openapi: 3.1.0
info:
  title: Adyen Recurring API
  description: "> The Recurring API is a legacy API for managing tokens. We strongly\
    \ recommend to use [Checkout API recurring endpoints](https://docs.adyen.com/api-explorer/Checkout/71/post/storedPaymentMethods)\
    \ instead when possible.\n\nThe Recurring API allows you to manage and remove\
    \ your tokens or stored payment details. Tokens should be created with validation\
    \ during a payment request.\n\nFor more information, refer to our [Tokenization\
    \ documentation](https://docs.adyen.com/online-payments/tokenization).\n## Authentication\n\
    You need an [API credential](https://docs.adyen.com/development-resources/api-credentials)\
    \ to authenticate to the API.\n\nIf using an API key, add an `X-API-Key` header\
    \ with the API key as the value, for example:\n\n ```\ncurl\n-H \"Content-Type:\
    \ application/json\" \\\n-H \"X-API-Key: YOUR_API_KEY\" \\\n...\n```\n\nAlternatively,\
    \ you can use the username and password to connect to the API using basic authentication,\
    \ for example:\n\n```\ncurl\n-u \"ws@Company.YOUR_COMPANY_ACCOUNT\":\"YOUR_BASIC_AUTHENTICATION_PASSWORD\"\
    \ \\\n-H \"Content-Type: application/json\" \\\n...\n```\n\n## Versioning\nRecurring\
    \ API supports [versioning](https://docs.adyen.com/development-resources/versioning)\
    \ using a version suffix in the endpoint URL. This suffix has the following format:\
    \ \"vXX\", where XX is the version number.\n\nFor example:\n```\nhttps://pal-test.adyen.com/pal/servlet/Recurring/v30/disable\n\
    ```\n\n## Server-side API libraries\nWe provide open-source [server-side API libraries](https://docs.adyen.com/development-resources/libraries/)\
    \ in several languages: \n- PHP\n- Java\n- Node.js\n- .NET\n- Go\n- Python\n-\
    \ Ruby\n- Apex (beta)\n\nSee our [integration examples](https://github.com/adyen-examples#%EF%B8%8F-official-integration-examples)\
    \ for example uses of the libraries.\n\n## Developer resources\nRecurring API\
    \ is available through a Postman collection. Click the button below to create\
    \ a fork, then set the environment variables at **Environments**&nbsp;>&nbsp;**Adyen&nbsp;APIs**.\
    \ \n\n[![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/25716737-0d1ef0da-f5a1-4004-b24a-c5152c51dc7b?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D25716737-0d1ef0da-f5a1-4004-b24a-c5152c51dc7b%26entityType%3Dcollection%26workspaceId%3Da8d63f9f-cfc7-4810-90c5-9e0c60030d3e#?env%5BAdyen%20APIs%5D=W3sia2V5IjoiWC1BUEktS2V5IiwidmFsdWUiOiIiLCJlbmFibGVkIjp0cnVlLCJ0eXBlIjoic2VjcmV0In0seyJrZXkiOiJZT1VSX01FUkNIQU5UX0FDQ09VTlQiLCJ2YWx1ZSI6IiIsImVuYWJsZWQiOnRydWUsInR5cGUiOiJkZWZhdWx0In0seyJrZXkiOiJZT1VSX0NPTVBBTllfQUNDT1VOVCIsInZhbHVlIjoiIiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6ImRlZmF1bHQifSx7ImtleSI6IllPVVJfQkFMQU5DRV9QTEFURk9STSIsInZhbHVlIjoiIiwiZW5hYmxlZCI6dHJ1ZSwidHlwZSI6ImRlZmF1bHQifV0=)\n\
    \n\n## Going live\n\nTo authenticate to the live endpoints, you need an [API credential](https://docs.adyen.com/development-resources/api-credentials)\
    \ from your live Customer Area.\n\nThe live endpoint URLs contain a prefix which\
    \ is unique to your company account:\n```\n\nhttps://{PREFIX}-pal-live.adyenpayments.com/pal/servlet/Recurring/v30/disable\n\
    ```\n\nGet your `{PREFIX}` from your live Customer Area under **Developers** >\
    \ **API URLs** > **Prefix**."
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
  version: '30'
  x-publicVersion: true
servers:
- url: https://pal-test.adyen.com/pal/servlet/Recurring/v30
tags:
- name: General
paths:
  /disable:
    post:
      tags:
      - General
      summary: Disable stored payment details
      description: 'Disables stored payment details to stop charging a shopper with
        this particular recurring detail ID.


        For more information, refer to [Disable stored details](https://docs.adyen.com/online-payments/classic-integrations/classic-api-integration/tokenization/disable-stored-details).'
      operationId: post-disable
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DisableRequest'
            examples:
              disableARecurringContract:
                $ref: '#/components/examples/post-disable-disableARecurringContract'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DisableResult'
        '400':
          description: Bad Request - a problem reading or understanding the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized - authentication required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden - insufficient permissions to process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '422':
          description: Unprocessable Entity - a request validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error - the server could not process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      x-sortIndex: 2
      x-methodName: disable
  /listRecurringDetails:
    post:
      tags:
      - General
      summary: Get stored payment details
      description: 'Lists the stored payment details for a shopper, if there are any
        available. The recurring detail ID can be used with a regular authorisation
        request to charge the shopper. A summary of the payment detail is returned
        for presentation to the shopper.


        For more information, refer to [Retrieve stored details](https://docs.adyen.com/classic-integration/recurring-payments/retrieve-stored-details/).'
      operationId: post-listRecurringDetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecurringDetailsRequest'
            examples:
              listAllRecurringDetails:
                $ref: '#/components/examples/post-listRecurringDetails-listAllRecurringDetails'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecurringDetailsResult'
        '400':
          description: Bad Request - a problem reading or understanding the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized - authentication required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden - insufficient permissions to process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '422':
          description: Unprocessable Entity - a request validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error - the server could not process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      x-sortIndex: 1
      x-methodName: listRecurringDetails
  /notifyShopper:
    post:
      tags:
      - General
      summary: Ask issuer to notify the shopper
      description: Sends a request to the issuer so they can inform the shopper about
        the upcoming recurring payment. This endpoint is used only for local acquiring
        in India. For more information, refer to [Recurring card payments in India](https://docs.adyen.com/payment-methods/cards/cards-recurring-india).
      operationId: post-notifyShopper
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotifyShopperRequest'
            examples:
              notifyShopperOfUpcomingRecurringPayment:
                $ref: '#/components/examples/post-notifyShopper-notifyShopperOfUpcomingRecurringPayment'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotifyShopperResult'
              examples:
                notifyShopperOfUpcomingRecurringPayment:
                  $ref: '#/components/examples/post-notifyShopper-notifyShopperOfUpcomingRecurringPayment-200'
        '400':
          description: Bad Request - a problem reading or understanding the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized - authentication required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden - insufficient permissions to process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '422':
          description: Unprocessable Entity - a request validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '500':
          description: Internal Server Error - the server could not process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      x-sortIndex: 4
      x-methodName: notifyShopper
  /scheduleAccountUpdater:
    post:
      tags:
      - General
      summary: Schedule running the Account Updater
      description: 'When making the API call, you can submit either the credit card
        information, or the recurring detail reference and the shopper reference:

        * If the card information is provided, all the sub-fields for `card` are mandatory.

        * If the recurring detail reference is provided, the fields for `shopperReference`
        and `selectedRecurringDetailReference` are mandatory.'
      operationId: post-scheduleAccountUpdater
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleAccountUpdaterRequest'
            examples:
              scheduleAccountUpdaterWithCardData:
                $ref: '#/components/examples/post-scheduleAccountUpdater-scheduleAccountUpdaterWithCardData'
              scheduleAccountUpdaterWithTokenData:
                $ref: '#/components/examples/post-scheduleAccountUpdater-scheduleAccountUpdaterWithTokenData'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleAccountUpdaterResult'
              examples:
                scheduleAccountUpdaterWithCardData:
                  $ref: '#/components/examples/post-scheduleAccountUpdater-scheduleAccountUpdaterWithCardData-200'
                scheduleAccountUpdaterWithTokenData:
                  $ref: '#/components/examples/post-scheduleAccountUpdater-scheduleAccountUpdaterWithTokenData-200'
        '400':
          description: Bad Request - a problem reading or understanding the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '401':
          description: Unauthorized - authentication required.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '403':
          description: Forbidden - insufficient permissions to process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
        '422':
          description: Unprocessable Entity - a request validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
              examples:
                scheduleAccountUpdaterWithTokenData:
                  $ref: '#/components/examples/post-scheduleAccountUpdater-scheduleAccountUpdaterWithTokenData-422'
        '500':
          description: Internal Server Error - the server could not process the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceError'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      x-addedInVersion: '4'
      x-sortIndex: 3
      x-methodName: scheduleAccountUpdater
components:
  schemas:
    Address:
      type: object
      additionalProperties: false
      properties:
        city:
          type: string
          description: 'The name of the city. Maximum length: 3000 characters.'
          maxLength: 3000
        country:
          type: string
          description: 'The two-character ISO-3166-1 alpha-2 country code. For example,
            **US**.

            > If you don''t know the country or are not collecting the country from
            the shopper, provide `country` as `ZZ`.'
        houseNumberOrName:
          type: string
          description: 'The number or name of the house. Maximum length: 3000 characters.'
          maxLength: 3000
        postalCode:
          type: string
          description: A maximum of five digits for an address in the US, or a maximum
            of ten characters for an address in all other countries.
        stateOrProvince:
          type: string
          description: 'The two-character ISO 3166-2 state or province code. For example,
            **CA** in the US or **ON** in Canada.

            > Required for the US and Canada.'
        street:
          type: string
          description: 'The name of the street. Maximum length: 3000 characters.

            > The house number should not be included in this field; it should be
            separately provided via `houseNumberOrName`.'
          maxLength: 3000
      required:
      - city
      - country
      - houseNumberOrName
      - postalCode
      - street
    Amount:
      type: object
      additionalProperties: false
      properties:
        currency:
          type: string
          description: The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes#currency-codes)
            of the amount.
          maxLength: 3
          minLength: 3
        value:
          type: integer
          format: int64
          description: The numeric value of the amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes#minor-units).
      required:
      - currency
      - value
    BankAccount:
      type: object
      additionalProperties: false
      properties:
        bankAccountNumber:
          type: string
          description: The bank account number (without separators).
        bankCity:
          type: string
          description: The bank city.
          x-addedInVersion: '18'
        bankLocationId:
          type: string
          description: The location id of the bank. The field value is `nil` in most
            cases.
        bankName:
          type: string
          description: The name of the bank.
        bic:
          type: string
          description: The [Business Identifier Code](https://en.wikipedia.org/wiki/ISO_9362)
            (BIC) is the SWIFT address assigned to a bank. The field value is `nil`
            in most cases.
        countryCode:
          type: string
          description: 'Country code where the bank is located.


            A valid value is an ISO two-character country code (e.g. ''NL'').'
        iban:
          type: string
          description: The [International Bank Account Number](https://en.wikipedia.org/wiki/International_Bank_Account_Number)
            (IBAN).
        ownerName:
          type: string
          description: "The name of the bank account holder.\nIf you submit a name\
            \ with non-Latin characters, we automatically replace some of them with\
            \ corresponding Latin characters to meet the FATF recommendations. For\
            \ example:\n* \u03C712 is converted to ch12.\n* \xFCA is converted to\
            \ euA.\n* Peter M\xF8ller is converted to Peter Mller, because banks don't\
            \ accept '\xF8'.\nAfter replacement, the ownerName must have at least\
            \ three alphanumeric characters (A-Z, a-z, 0-9), and at least one of them\
            \ must be a valid Latin character (A-Z, a-z). For example:\n* John17 -\
            \ allowed.\n* J17 - allowed.\n* 171 - not allowed.\n* John-7 - allowed.\n\
            > If provided details don't match the required format, the response returns\
            \ the error message: 203 'Invalid bank account holder name'."
        taxId:
          type: string
          description: The bank account holder's tax ID.
          x-addedInVersion: '18'
    Card:
      type: object
      additionalProperties: false
      properties:
        cvc:
          type: string
          description: "The [card verification code](https://docs.adyen.com/payments-fundamentals/payment-glossary#card-security-code-cvc-cvv-cid)\
            \ (1-20 characters). Depending on the card brand, it is known also as:\n\
            * CVV2/CVC2 \u2013 length: 3 digits\n* CID \u2013 length: 4 digits\n>\
            \ If you are using [Client-Side Encryption](https://docs.adyen.com/classic-integration/cse-integration-ecommerce),\
            \ the CVC code is present in the encrypted data. You must never post the\
            \ card details to the server.\n> This field must be always present in\
            \ a [one-click payment request](https://docs.adyen.com/classic-integration/recurring-payments).\n\
            > When this value is returned in a response, it is always empty because\
            \ it is not stored."
          maxLength: 20
          minLength: 1
        expiryMonth:
          type: string
          description: 'The card expiry month.

            Format: 2 digits, zero-padded for single digits. For example:

            * 03 = March

            * 11 = November'
          maxLength: 2
          minLength: 1
        expiryYear:
          type: string
          description: 'The card expiry year.

            Format: 4 digits. For example: 2020'
          maxLength: 4
          minLength: 4
        holderName:
          type: string
          description: The name of the cardholder, as printed on the card.
          maxLength: 50
          minLength: 1
        issueNumber:
          type: string
          description: The issue number of the card (for some UK debit cards only).
          maxLength: 2
          minLength: 1
        number:
          type: string
          description: 'The card number (4-19 characters). Do not use any separators.

            When this value is returned in a response, only the last 4 digits of the
            card number are returned.'
          maxLength: 19
          minLength: 4
        startMonth:
          type: string
          description: The month component of the start date (for some UK debit cards
            only).
          maxLength: 2
          minLength: 1
        startYear:
          type: string
          description: The year component of the start date (for some UK debit cards
            only).
          maxLength: 4
          minLength: 4
    DisableRequest:
      type: object
      additionalProperties: false
      properties:
        contract:
          type: string
          description: 'Specify the contract if you only want to disable a specific
            use.


            This field can be set to one of the following values, or to their combination
            (comma-separated):

            * ONECLICK

            * RECURRING

            * PAYOUT'
          x-addedInVersion: '3'
        merchantAccount:
          type: string
          description: The merchant account identifier with which you want to process
            the transaction.
        recurringDetailReference:
          type: string
          description: 'The ID that uniquely identifies the recurring detail reference.


            If it is not provided, the whole recurring contract of the `shopperReference`
            will be disabled, which includes all recurring details.'
        shopperReference:
          type: string
          description: 'The ID that uniquely identifies the shopper.


            This `shopperReference` must be the same as the `shopperReference` used
            in the initial payment.'
      required:
      - merchantAccount
      - shopperReference
    DisableResult:
      type: object
      additionalProperties: false
      properties:
        response:
          type: string
          description: Depending on whether a specific recurring detail was in the
            request, result is either [detail-successfully-disabled] or [all-details-successfully-disabled].
    Name:
      type: object
      additionalProperties: false
      properties:
        firstName:
          type: string
          description: The first name.
          maxLength: 80
        lastName:
          type: string
          description: The last name.
          maxLength: 80
      required:
      - firstName
      - lastName
    NotifyShopperRequest:
      type: object
      additionalProperties: false
      properties:
        amount:
          $ref: '#/components/schemas/Amount'
          description: The amount of the upcoming payment.
        billingDate:
          type: string
          description: Date on which the subscription amount will be debited from
            the shopper. In YYYY-MM-DD format
        billingSequenceNumber:
          type: string
          description: Sequence of the debit. Depends on Frequency and Billing Attempts
            Rule.
        displayedReference:
          type: string
          description: Reference of Pre-debit notification that is displayed to the
            shopper. Optional field. Maps to reference if missing
        merchantAccount:
          type: string
          description: The merchant account identifier with which you want to process
            the transaction.
        recurringDetailReference:
          type: string
          description: This is the `recurringDetailReference` returned in the response
            when you created the token.
        reference:
          type: string
          description: Pre-debit notification reference sent by the merchant. This
            is a mandatory field
        shopperReference:
          type: string
          description: 'The ID that uniquely identifies the shopper.


            This `shopperReference` must be the same as the `shopperReference` used
            in the initial payment.'
        storedPaymentMethodId:
          type: string
          description: This is the `recurringDetailReference` returned in the response
            when you created the token.
      required:
      - amount
      - merchantAccount
      - reference
      - shopperReference
    NotifyShopperResult:
      type: object
      additionalProperties: false
      properties:
        displayedReference:
          type: string
          description: Reference of Pre-debit notification that is displayed to the
            shopper
        message:
          type: string
          description: A simple description of the `resultCode`.
        pspReference:
          type: string
          description: The unique reference that is associated with the request.
        reference:
          type: string
          description: Reference of Pre-debit notification sent in my the merchant
        resultCode:
          type: string
          description: The code indicating the status of notification.
        shopperNotificationReference:
          type: string
          description: The unique reference for the request sent downstream.
        storedPaymentMethodId:
          type: string
          description: This is the recurringDetailReference returned in the response
            when token was created
    Recurring:
      type: object
      additionalProperties: false
      properties:
        contract:
          type: string
          description: "The type of recurring contract to be used.\nPossible values:\n\
            * `ONECLICK` \u2013 Payment details can be used to initiate a one-click\
            \ payment, where the shopper enters the [card security code (CVC/CVV)](https://docs.adyen.com/payments-fundamentals/payment-glossary#card-security-code-cvc-cvv-cid).\n\
            * `RECURRING` \u2013 Payment details can be used without the card security\
            \ code to initiate [card-not-present transactions](https://docs.adyen.com/payments-fundamentals/payment-glossary#card-not-present-cnp).\n\
            * `ONECLICK,RECURRING` \u2013 Payment details can be used regardless of\
            \ whether the shopper is on your site or not.\n* `PAYOUT` \u2013 Payment\
            \ details can be used to [make a payout](https://docs.adyen.com/online-payments/online-payouts).\n\
            * `EXTERNAL` - Use this when you store payment details and send the raw\
            \ card number or network token directly in your API request.\n"
          enum:
          - ONECLICK
          - ONECLICK,RECURRING
          - RECURRING
          - PAYOUT
          - EXTERNAL
        recurringDetailName:
          type: string
          description: A descriptive name for this detail.
        tokenService:
          type: string
          description: The name of the token service.
          enum:
          - VISATOKENSERVICE
          - MCTOKENSERVICE
          - AMEXTOKENSERVICE
          - TOKEN_SHARING
          x-addedInVersion: '25'
    RecurringDetail:
      type: object
      additionalProperties: false
      properties:
        additionalData:
          type: object
          additionalProperties:
            type: string
          description: 'This field contains additional data, which may be returned
            in a particular response.


            The additionalData object consists of entries, each of which includes
            the key and value.'
          x-addedInVersion: '5'
        alias:
          type: string
          description: 'The alias of the credit card number.


            Applies only to recurring contracts storing credit card details'
          x-addedInVersion: '4'
        aliasType:
          type: string
          description: 'The alias type of the credit card number.


            Applies only to recurring contracts storing credit card details.'
          x-addedInVersion: '4'
        bank:
          $ref: '#/components/schemas/BankAccount'
          description: A container for bank account data.
        billingAddress:
          $ref: '#/components/schemas/Address'
          description: The billing address.
          x-addedInVersion: '4'
        card:
          $ref: '#/components/schemas/Card'
          description: A container for card data.
        contractTypes:
          type: array
          description: Types of recurring contracts.
          items:
            type: string
          x-addedInVersion: '12'
        creationDate:
          type: string
          format: date-time
          description: The date when the recurring details were created.
        firstPspReference:
          type: string
          description: The `pspReference` of the first recurring payment that created
            the recurring detail.
          x-addedInVersion: '4'
        name:
          type: string
          description: An optional descriptive name for this recurring detail.
        paymentMethodVariant:
          type: string
          description: The  type or sub-brand of a payment method used, e.g. Visa
            Debit, Visa Corporate, etc. For more information, refer to [PaymentMethodVariant](https://docs.adyen.com/development-resources/paymentmethodvariant).
          x-addedInVersion: '2'
        recurringDetailReference:
          type: string
          description: The reference that uniquely identifies the recurring detail.
        shopperName:
          $ref: '#/components/schemas/Name'
          description: The name of the shopper.
          x-addedInVersion: '4'
        socialSecurityNumber:
          type: string
          description: A shopper's social security number (only in countries where
            it is legal to collect).
          x-addedInVersion: '4'
        tokenDetails:
          $ref: '#/components/schemas/TokenDetails'
          x-addedInVersion: '2'
        variant:
          type: string
          description: "The payment method, such as \u201Cmc\", \"visa\", \"ideal\"\
            , \"paypal\"."
      required:
      - recurringDetailReference
      - variant
    RecurringDetailWrapper:
      properties:
        RecurringDetail:
          $ref: '#/components/schemas/RecurringDetail'
    RecurringDetailsRequest:
      type: object
      additionalProperties: false
      properties:
        merchantAccount:
          type: string
          description: The merchant account identifier you want to process the (transaction)
            request with.
        recurring:
          $ref: '#/components/schemas/Recurring'
          description: 'A container for the type of a recurring contract to be retrieved.


            The contract value needs to match the contract value submitted in the
            payment transaction used to create a recurring contract.

            However, if `ONECLICK,RECURRING` is the original contract definition in
            the initial payment, then `contract` should take either `ONECLICK` or
            `RECURRING`, depending on whether or not you want the shopper to enter
            their card''s security code when they finalize their purchase.'
        shopperReference:
          type: string
          description: The reference you use to uniquely identify the shopper (e.g.
            user ID or account ID).
      required:
      - merchantAccount
      - shopperReference
    RecurringDetailsResult:
      type: object
      additionalProperties: false
      properties:
        creationDate:
          type: string
          format: date-time
          description: The date when the recurring details were created.
        details:
          type: array
          description: Payment details stored for recurring payments.
          items:
            $ref: '#/components/schemas/RecurringDetailWrapper'
        lastKnownShopperEmail:
          type: string
          description: The most recent email for this shopper (if available).
        shopperReference:
          type: string
          description: The reference you use to uniquely identify the shopper (e.g.
            user ID or account ID).
    ScheduleAccountUpdaterRequest:
      type: object
      additionalProperties: false
      properties:
        additionalData:
          type: object
          additionalProperties:
            type: string
          description: This field contains additional data, which may be required
            for a particular request.
        card:
          $ref: '#/components/schemas/Card'
          description: 'Credit card data.


            Optional if `shopperReference` and `selectedRecurringDetailReference`
            are provided.'
        merchantAccount:
          type: string
          description: Account of the merchant.
        reference:
          type: string
          description: A reference that merchants can apply for the call.
        selectedRecurringDetailReference:
          type: string
          description: 'The selected detail recurring reference.


            Optional if `card` is provided.'
        shopperReference:
          type: string
          description: 'The reference of the shopper that owns the recurring contract.


            Optional if `card` is provided.'
      required:
      - merchantAccount
      - reference
    ScheduleAccountUpdaterResult:
      type: object
      additionalProperties: false
      properties:
        pspReference:
          type: string
          description: Adyen's 16-character unique reference associated with the transaction.
            This value is globally unique; quote it when communicating with us about
            this request.
        result:
          type: string
          description: The result of scheduling an Account Updater. If scheduling
            was successful, this field returns **Success**; otherwise it contains
            the error message.
      required:
      - pspReference
      - result
    ServiceError:
      type: object
      additionalProperties: false
      properties:
        errorCode:
          type: string
          description: The error code mapped to the error message.
        errorType:
          type: string
          description: The category of the error.
        message:
          type: string
          description: A short explanation of the issue.
        pspReference:
          type: string
          description: The PSP reference of the payment.
        status:
          type: integer
          format: int32
          description: The HTTP response status.
    TokenDetails:
      type: object
      additionalProperties: false
      properties:
        tokenData:
          type: object
          additionalProperties:
            type: string
        tokenDataType:
          type: string
  examples:
    post-disable-disableARecurringContract:
      summary: Disable a recurring contract
      value:
        shopperReference: YOUR_SHOPPER_REFERENCE
        recurringDetailReference: '8314442372419167'
        merchantAccount: YOUR_MERCHANT_ACCOUNT
    post-listRecurringDetails-listAllRecurringDetails:
      summary: List recurring details of the specified contract value
      value:
        recurring:
          contract: RECURRING
        shopperReference: YOUR_SHOPPER_REFERENCE
        merchantAccount: YOUR_MERCHANT_ACCOUNT
    post-notifyShopper-notifyShopperOfUpcomingRecurringPayment:
      summary: Request issuer to notify shopper of upcoming recurring payment
      value:
        merchantAccount: YOUR_MERCHANT_ACCOUNT
        storedPaymentMethodId: '8415995487234100'
        shopperReference: YOUR_SHOPPER_REFERENCE
        amount:
          currency: INR
          value: 1000
        billingDate: '2021-03-16'
        reference: Example reference
        displayedReference: exampleDisplayedReference
    post-notifyShopper-notifyShopperOfUpcomingRecurringPayment-200:
      summary: Example response for request 'notifyShopper'
      value:
        message: Request Processed Successfully
        resultCode: Success
        shopperNotificationReference: '9915003646742627'
        storedPaymentMethodId: '8415995487234100'
        pspReference: M5N7TQ4TG5PFWR50
        reference: Example reference
        displayedReference: exampleDisplayedReference
    post-scheduleAccountUpdater-scheduleAccountUpdaterWithCardData:
      summary: Schedule AccountUpdater with card data
      value:
        merchantAccount: YOUR_MERCHANT_ACCOUNT
        reference: YOUR_REFERENCE
        card:
          expiryMonth: '03'
          expiryYear: '2030'
          holderName: Adyen Test
          number: '4111111111111111'
    post-scheduleAccountUpdater-scheduleAccountUpdaterWithCardData-200:
      summary: Scheduled Account Updater with card data
      value:
        pspReference: QFQTPCQ8HXSKGK82
        result: Success
    post-scheduleAccountUpdater-scheduleAccountUpdaterWithTokenData:
      summary: Schedule AccountUpdater with token data
      value:
        merchantAccount: YOUR_MERCHANT_ACCOUNT
        reference: YOUR_REFERENCE
        shopperReference: YOUR_SHOPPER_REFERENCE
        selectedRecurringDetailReference: '8814232895168272'
    post-scheduleAccountUpdater-scheduleAccountUpdaterWithTokenData-200:
      summary: Scheduled Account Updater with token data
      value:
        pspReference: JLCMPCQ8HXSKGK82
        result: Success
    post-scheduleAccountUpdater-scheduleAccountUpdaterWithTokenData-422:
      summary: Error response for RecurringShopper not found
      value:
        status: 422
        errorCode: '000'
        message: RecurringShopper not found
        errorType: validation
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    BasicAuth:
      type: http
      scheme: basic
