openapi: 3.1.0
info:
  title: Tokenization webhooks
  description: "With Adyen, you can securely store payment details of your shoppers\
    \ with their consent. We refer to these saved payment details as tokens.\n\n We\
    \ use webhooks to inform you about token lifecycle events. For more information,\
    \ refer to our [documentation](https://docs.adyen.com/online-payments/tokenization/)."
  termsOfService: https://www.adyen.com/legal/terms-and-conditions
  contact:
    name: Adyen Developer Experience team
    url: https://github.com/Adyen/adyen-openapi
  version: '1'
  x-publicVersion: true
tags:
- name: General
components:
  schemas:
    RecurringToken:
      type: object
      additionalProperties: false
      properties:
        merchantAccount:
          type: string
          description: The identifier of the merchant account related to the event
            that triggered the webhook.
        shopperReference:
          type: string
          description: Your unique shopper reference that is associated with the `storedPaymentMethodId`.
        storedPaymentMethodId:
          type: string
          description: The ID of the token.
        type:
          type: string
          description: The type of the payment method.
      required:
      - merchantAccount
      - shopperReference
      - storedPaymentMethodId
      - type
    RecurringTokenStoreOperation:
      type: object
      additionalProperties: false
      properties:
        merchantAccount:
          type: string
          description: The identifier of the merchant account related to the event
            that triggered the webhook.
        operation:
          type: string
          description: A text description that provides details about the operation,
            intended for audit purposes.
        shopperReference:
          type: string
          description: Your unique shopper reference that is associated with the `storedPaymentMethodId`.
        storedPaymentMethodId:
          type: string
          description: The ID of the token.
        type:
          type: string
          description: The type of the payment method.
      required:
      - merchantAccount
      - operation
      - shopperReference
      - storedPaymentMethodId
      - type
    TokenizationAlreadyExistingDetailsNotificationRequest:
      type: object
      additionalProperties: false
      properties:
        createdAt:
          type: string
          format: date-time
          description: The date and time when the event happened, in ISO 8601 extended
            format.
          example: '2024-10-29T16:15:29+01:00'
        data:
          $ref: '#/components/schemas/RecurringTokenStoreOperation'
          description: Contains event details.
        environment:
          type: string
          description: 'The environment from which the webhook originated.


            Possible values: **test**, **live**.'
          enum:
          - test
          - live
          example: live
        eventId:
          type: string
          description: The PSP reference of the event that triggered the webhook.
        type:
          type: string
          description: The type of webhook.
          enum:
          - recurring.token.alreadyExisting
        version:
          type: string
          description: The version of this entity.
          example: '1'
      required:
      - createdAt
      - data
      - environment
      - eventId
      - type
    TokenizationCreatedDetailsNotificationRequest:
      type: object
      additionalProperties: false
      properties:
        createdAt:
          type: string
          format: date-time
          description: The date and time when the event happened, in ISO 8601 extended
            format.
          example: '2024-10-29T16:15:29+01:00'
        data:
          $ref: '#/components/schemas/RecurringTokenStoreOperation'
          description: Contains event details.
        environment:
          type: string
          description: 'The environment from which the webhook originated.


            Possible values: **test**, **live**.'
          enum:
          - test
          - live
          example: live
        eventId:
          type: string
          description: The PSP reference of the event that triggered the webhook.
        type:
          type: string
          description: The type of webhook.
          enum:
          - recurring.token.created
        version:
          type: string
          description: The version of this entity.
          example: '1'
      required:
      - createdAt
      - data
      - environment
      - eventId
      - type
    TokenizationDisabledDetailsNotificationRequest:
      type: object
      additionalProperties: false
      properties:
        createdAt:
          type: string
          format: date-time
          description: The date and time when the event happened, in ISO 8601 extended
            format.
          example: '2024-10-29T16:15:29+01:00'
        data:
          $ref: '#/components/schemas/RecurringToken'
          description: Contains event details.
        environment:
          type: string
          description: 'The environment from which the webhook originated.


            Possible values: **test**, **live**.'
          enum:
          - test
          - live
          example: live
        eventId:
          type: string
          description: The PSP reference of the event that triggered the webhook.
        type:
          type: string
          description: The type of webhook.
          enum:
          - recurring.token.disabled
        version:
          type: string
          description: The version of this entity.
          example: '1'
      required:
      - createdAt
      - data
      - environment
      - eventId
      - type
    TokenizationNotificationResponse:
      type: object
      additionalProperties: false
      properties:
        notificationResponse:
          type: string
          description: Respond with any **2xx** HTTP status code to [accept the webhook](https://docs.adyen.com/development-resources/webhooks/#accept-webhooks).
    TokenizationUpdatedDetailsNotificationRequest:
      type: object
      additionalProperties: false
      properties:
        createdAt:
          type: string
          format: date-time
          description: The date and time when the event happened, in ISO 8601 extended
            format.
          example: '2024-10-29T16:15:29+01:00'
        data:
          $ref: '#/components/schemas/RecurringTokenStoreOperation'
          description: Contains event details.
        environment:
          type: string
          description: 'The environment from which the webhook originated.


            Possible values: **test**, **live**.'
          enum:
          - test
          - live
          example: live
        eventId:
          type: string
          description: The PSP reference of the event that triggered the webhook.
        type:
          type: string
          description: The type of webhook.
          enum:
          - recurring.token.updated
        version:
          type: string
          description: The version of this entity.
          example: '1'
      required:
      - createdAt
      - data
      - environment
      - eventId
      - type
  examples:
    post-recurring.token.alreadyExisting-recurring-token-alreadyExisting:
      summary: Token already exists
      value:
        createdAt: '2025-06-30T16:40:23+02:00'
        eventId: QBQQ9DLNRHHKGK38
        environment: test
        data:
          merchantAccount: YOUR_MERCHANT_ACCOUNT
          storedPaymentMethodId: M5N7TQ4TG5PFWR50
          type: visastandarddebit
          operation: alreadyExisting
          shopperReference: YOUR_SHOPPER_REFERENCE
        type: recurring.token.alreadyExisting
    post-recurring.token.created-recurring-token-created:
      summary: Token is created
      value:
        createdAt: '2025-06-30T16:40:23+02:00'
        eventId: QBQQ9DLNRHHKGK38
        environment: test
        data:
          merchantAccount: YOUR_MERCHANT_ACCOUNT
          storedPaymentMethodId: M5N7TQ4TG5PFWR50
          type: visastandarddebit
          operation: created
          shopperReference: YOUR_SHOPPER_REFERENCE
        type: recurring.token.created
    post-recurring.token.disabled-recurring-token-disabled:
      summary: Token is disabled
      value:
        createdAt: '2025-06-30T16:40:23+02:00'
        eventId: QBQQ9DLNRHHKGK38
        environment: test
        data:
          merchantAccount: YOUR_MERCHANT_ACCOUNT
          storedPaymentMethodId: M5N7TQ4TG5PFWR50
          type: visastandarddebit
          shopperReference: YOUR_SHOPPER_REFERENCE
        type: recurring.token.disabled
    post-recurring.token.updated-recurring-token-updated:
      summary: Token details are updated
      value:
        createdAt: '2025-06-30T16:40:23+02:00'
        eventId: QBQQ9DLNRHHKGK38
        environment: test
        data:
          merchantAccount: YOUR_MERCHANT_ACCOUNT
          storedPaymentMethodId: M5N7TQ4TG5PFWR50
          type: visastandarddebit
          operation: updated
          shopperReference: YOUR_SHOPPER_REFERENCE
        type: recurring.token.updated
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
webhooks:
  recurring.token.alreadyExisting:
    post:
      tags:
      - General
      summary: Token already exists
      description: Adyen sends this webhook when you attempt to create or update a
        token with details that match an already existing token.
      operationId: post-recurring.token.alreadyExisting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenizationAlreadyExistingDetailsNotificationRequest'
            examples:
              recurring-token-alreadyExisting:
                $ref: '#/components/examples/post-recurring.token.alreadyExisting-recurring-token-alreadyExisting'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenizationNotificationResponse'
      security:
      - BasicAuth: []
      x-sortIndex: 0
      x-methodName: tokenAlreadyExists
  recurring.token.created:
    post:
      tags:
      - General
      summary: Token created
      description: Adyen sends this webhook when a token is created.
      operationId: post-recurring.token.created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenizationCreatedDetailsNotificationRequest'
            examples:
              recurring-token-created:
                $ref: '#/components/examples/post-recurring.token.created-recurring-token-created'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenizationNotificationResponse'
      security:
      - BasicAuth: []
      x-sortIndex: 0
      x-methodName: tokenCreated
  recurring.token.disabled:
    post:
      tags:
      - General
      summary: Token disabled
      description: Adyen sends this webhook when a token is disabled. For example,
        when you [delete stored payment details](https://docs.adyen.com/online-payments/tokenization/managing-tokens/#delete-stored-details),
        or when a third party disables the payment details.
      operationId: post-recurring.token.disabled
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenizationDisabledDetailsNotificationRequest'
            examples:
              recurring-token-disabled:
                $ref: '#/components/examples/post-recurring.token.disabled-recurring-token-disabled'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenizationNotificationResponse'
      security:
      - BasicAuth: []
      x-sortIndex: 0
      x-methodName: tokenDisabled
  recurring.token.updated:
    post:
      tags:
      - General
      summary: Token updated
      description: Adyen sends this webhook when a token is updated, for example,
        when you [update stored details](https://docs.adyen.com/online-payments/tokenization/managing-tokens/#update-stored-details).
        Tokens can also be updated by card networks.
      operationId: post-recurring.token.updated
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenizationUpdatedDetailsNotificationRequest'
            examples:
              recurring-token-updated:
                $ref: '#/components/examples/post-recurring.token.updated-recurring-token-updated'
      responses:
        '200':
          description: OK - the request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenizationNotificationResponse'
      security:
      - BasicAuth: []
      x-sortIndex: 0
      x-methodName: tokenUpdated
